"""Add due_date and customer_gstin

Revision ID: 3350e41c9121
Revises: 48edc730fb4e
Create Date: 2026-09-16 11:36:50.304373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3350e41c9121'
down_revision: Union[str, Sequence[str], None] = '48edc730fb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('transactions', sa.Column('vendor_gstin', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('customer_gstin', sa.String(), nullable=True))
    op.drop_column('transactions', 'gstin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('gstin', sa.VARCHAR(), nullable=True))
    op.drop_column('transactions', 'customer_gstin')
    op.drop_column('transactions', 'vendor_gstin')
    op.drop_column('transactions', 'due_date')
    # ### end Alembic commands ###
