"""Add anomalies and currency to Transaction

Revision ID: c5f6295c80ab
Revises: 3350e41c9121
Create Date: 2026-09-16 14:38:08.214454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f6295c80ab'
down_revision: Union[str, Sequence[str], None] = '3350e41c9121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('anomalies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'anomalies')
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###
